spring:
  application:
    name: user-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: root
#    password: root
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
      database: userdb
server:
  port: 8082