spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
      database: userdb
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
