spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user_db

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

